# Generated by Django 3.2.16 on 2022-11-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(default='', max_length=256)),
                ('product_name', models.CharField(default='', max_length=256)),
                ('product_num', models.IntegerField(null=True)),
                ('categories', models.TextField(null=True)),
                ('img_src', models.CharField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=256)),
                ('score', models.FloatField(default=0, null=True)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analysisApp.productmodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=20)),
                ('summarization', models.CharField(default='', max_length=256)),
                ('keyword_score', models.FloatField(default=0)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analysisApp.productmodel')),
            ],
            options={
                'db_table': 'PDkeyword',
            },
        ),
    ]
