# Generated by Django 3.2.16 on 2022-11-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='score',
        ),
        migrations.AddField(
            model_name='productkeyword',
            name='keyword_frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.CharField(max_length=1000),
        ),
    ]
