# Generated by Django 3.2.16 on 2022-11-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisApp', '0002_auto_20221120_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_num',
            new_name='product_id',
        ),
    ]
